### ISSUE TITLE
NFC服务FC

### ISSUE THREAD

**Issue by qiuyouxin** [canyie/Dreamland#17]
问题：使用模块thanox，激活后NFC服务无限fc

系统：lg 8.0

ed和旧版lsp都没有这个问题。THANOX那边说是nfc权限问题，附件是thanox提取的logs。希望大佬有空看下能否解决这个BUG.

[thanos_logs.zip](https://github.com/canyie/Dreamland/files/7231959/thanos_logs.zip)

**Comment by qiuyouxin** [comment]
激活模块thanox后boot.log，希望有帮助。
[boot.log](https://github.com/canyie/Dreamland/files/7232085/boot.log)

**Comment by FarahJafrinFJ** [comment]
![Screenshot_20211001-114449.jpg](https://user-images.githubusercontent.com/75559397/135571546-95260427-e139-4c3c-966a-6579b43494af.jpg)
