### ISSUE TITLE
Zygisk support?

### ISSUE THREAD

**Issue by skelletR** [canyie/Dreamland#20]
Zygisk support if it is possible, The other xposed can't install because old phone, Sony Xperia Z5 android 7.1.1

**Comment by canyie** [comment]
c24cb0ae00fa590d6f883e738b894d69167d38be

**Comment by skelletR** [comment]
> [c24cb0a](https://github.com/canyie/Dreamland/commit/c24cb0ae00fa590d6f883e738b894d69167d38be)

Where can download the version with zygisk? I download one from pipeline, is good? Or must make it myself in android studio?

**Comment by HuskyDG** [comment]
> > [c24cb0a](https://github.com/canyie/Dreamland/commit/c24cb0ae00fa590d6f883e738b894d69167d38be)
> 
> Where can download the version with zygisk? I download one from pipeline, is good? Or must make it myself in android studio?

[Download here](https://dev.azure.com/ssz33334930121/ssz3333493/_build/results?buildId=71&view=artifacts&pathAsName=false&type=publishedArtifacts)

**Comment by skelletR** [comment]
> > > [c24cb0a](https://github.com/canyie/Dreamland/commit/c24cb0ae00fa590d6f883e738b894d69167d38be)
> > 
> > 
> > Where can download the version with zygisk? I download one from pipeline, is good? Or must make it myself in android studio?
> 
> [Download here](https://dev.azure.com/ssz33334930121/ssz3333493/_build/results?buildId=71&view=artifacts&pathAsName=false&type=publishedArtifacts)

This i have download, and thanks you make it work with zygisk

**Comment by HuskyDG** [comment]
> > > > [c24cb0a](https://github.com/canyie/Dreamland/commit/c24cb0ae00fa590d6f883e738b894d69167d38be)
> > > 
> > > 
> > > Where can download the version with zygisk? I download one from pipeline, is good? Or must make it myself in android studio?
> > 
> > 
> > [Download here](https://dev.azure.com/ssz33334930121/ssz3333493/_build/results?buildId=71&view=artifacts&pathAsName=false&type=publishedArtifacts)
> 
> This i have download, and thanks you make it work with zygisk

Thank canyie, not me :)

**Comment by skelletR** [comment]
> > > > > [c24cb0a](https://github.com/canyie/Dreamland/commit/c24cb0ae00fa590d6f883e738b894d69167d38be)
> > > > 
> > > > 
> > > > Where can download the version with zygisk? I download one from pipeline, is good? Or must make it myself in android studio?
> > > 
> > > 
> > > [Download here](https://dev.azure.com/ssz33334930121/ssz3333493/_build/results?buildId=71&view=artifacts&pathAsName=false&type=publishedArtifacts)
> > 
> > 
> > This i have download, and thanks you make it work with zygisk
> 
> Thank canyie, not me :)

Oh, I thought canyie answer me and reply, and HuskyDG your work is very good just yesterday download latest magisk from you and apply on bluestacks

**Comment by skelletR** [comment]
Thank canyie, just test it all work good.
