### ISSUE TITLE
哔哩漫游在最新版本失效

### ISSUE THREAD

**Issue by weargle** [canyie/Dreamland#22]
安装了最新版本2101，使用后发现哔哩漫游失效了，哔哩漫游版本1.5.7。
在lsp好好的，换成梦境失效了。

**Comment by duzhaokun123** [comment]
@weargle 首先更新哔哩漫游到最新 ci

**Comment by weargle** [comment]
> @weargle 首先更新哔哩漫游到最新 ci

一定要更新到最新1.5.8吗，我这个版本属于次新版，我感觉不可能说最新版支持次新版不支持的问题，最新版删除一个功能我有点不想更新

**Comment by duzhaokun123** [comment]
@weargle 因为你没提供 哔哩哔哩 版本
假设为 6.62

**Comment by weargle** [comment]
> @weargle 因为你没提供 哔哩哔哩 版本
> 假设为 6.62

哔哩哔哩6.57

**Comment by weargle** [comment]
> @weargle 因为你没提供 哔哩哔哩 版本
> 假设为 6.62

我刚把lsp换成梦境就失效了

**Comment by weargle** [comment]
微x在换成梦境一样失效了

**Comment by canyie** [comment]
需要提供 Android 版本，应用和模块页怎么勾选的，及 log。

**Comment by weargle** [comment]
> 需要提供 Android 版本，应用和模块页怎么勾选的，及 log。

安卓11，日志不知道怎么提供
![Screenshot_2022-03-06-00-03-27-201_top.canyie.dreamland.manager.jpg](https://user-images.githubusercontent.com/26951765/156891061-a2480eb3-8417-413a-a593-406ba7e697ae.jpg)
![Screenshot_2022-03-06-00-03-12-556_top.canyie.dreamland.manager.jpg](https://user-images.githubusercontent.com/26951765/156891075-dffcd7df-5b1c-4353-a7d8-3cc395dca81d.jpg)

**Comment by cracky5322** [comment]
@weargle 壓縮上傳，或使用線上服務[線上服務](https://pastebin.com/) 黏貼日誌

**Comment by weargle** [comment]
> @weargle 壓縮上傳，或使用線上服務[線上服務](https://pastebin.com/) 黏貼日誌

我说的话有些错误，我重新修改了

**Comment by weargle** [comment]
我更新哔哩漫游到1.5.9好了，哔哩漫游重新生效了
