### ISSUE TITLE
使用MIUI 主题破解模块列表中没有显示此模块

### ISSUE THREAD

**Issue by wangzhenxing4** [canyie/Dreamland#23]
设备:M2011K2C
android版本:12
MIUI版本:13.0.5
使用框架:zy版梦境
出现问题:使用MIUI 主题破解模块列表中没有显示此模块
解决方法:无
出现几率:100%

**Comment by duzhaokun123** [comment]
[MIUI 主题破解](https://github.com/qqlittleice/FuckMiuiThemeManager)

没有定义`xposedmodule: true` 某种意义上他不是 xposed 模块

应向模块开发者反馈该问题

**Comment by wangzhenxing4** [comment]
好的！
