### ISSUE TITLE
无法准确识别推荐的作用域

### ISSUE THREAD

**Issue by wangzhenxing4** [canyie/Dreamland#24]
设备:M2011K2C
android版本:12
MIUI版本:13.0.5
使用框架:zy版梦境
出现问题:部分模块无法显示出推荐的作用域
解决方法:无
出现几率:100%

**Comment by wangzhenxing4** [comment]
> @wangzhenxing4 模块不写作用域管框架什么事

使用lsposed框架可以正常显示

**Comment by duzhaokun123** [comment]
这时候就需要举出具体模块文件了

**Comment by wangzhenxing4** [comment]
如果我没有记错的话，好像是chimi，https://github.com/yonghen/chimi-
