### ISSUE TITLE
咨询此模块集成到aosp 源码

### ISSUE THREAD

**Issue by biaolv** [canyie/Dreamland#27]
你好作者，我想把此模块集成到aosp源码中，无需通过magisk模块安装。通过编译源码打包成rom。作者能给出相关集成方法么？

**Comment by hhhaiai** [comment]
+1

**Comment by hhhaiai** [comment]
@biaolv 直接内置到framework，是否可行？

**Comment by canyie** [comment]
没那么简单，还要改 sepolicy 添加 `allow system_server:system_server process execmem` 这条规则。

**Comment by hhhaiai** [comment]
> 没那么简单，还要改 sepolicy 添加 `allow system_server:system_server process execmem` 这条规则。

要编译到aosp系统，这个应该可以修改。  需要增加策略，需要内置文件，还有其他的吗

**Comment by canyie** [comment]
应该没了

**Comment by wj2008** [comment]
方案可行， 这几天看了一下 已经成功内置进Lineage 20了, 在zygote init的时候注入pine，感谢作者！

**Comment by df13954** [comment]
> > 没那么简单，还要改 sepolicy 添加 `allow system_server:system_server process execmem` 这条规则。
> 
> 要编译到aosp系统，这个应该可以修改。 需要增加策略，需要内置文件，还有其他的吗

你好啊，如何集成到AOSP中呢，有没有详细的步骤分享一下
