### ISSUE TITLE
android 10.0 magisk root 安装失败

### ISSUE THREAD

**Issue by enjoyMiracle** [canyie/Dreamland#3]
mount 失败
![image](https://user-images.githubusercontent.com/38520010/75128465-2c69c580-56ff-11ea-9c66-7f4dce7d0b4d.png)

**Comment by ggggskd** [comment]
目前不支持安卓10！

**Comment by canyie** [comment]
暂时不支持Android 10，以后会出magisk模块来安装（不过估计得等很久…）

**Comment by canyie** [comment]
已经出了面具模块，群里可以下载（鬼知道我到底有多能鸽233）
