### ISSUE TITLE
2102支持安卓5-6，那怎么才能安装呢？

### ISSUE THREAD

**Issue by nl745200** [canyie/Dreamland#31]
安卓5不支持magisk呀

**Comment by canyie** [comment]
我自己在安卓5上测试过 magisk 能正常用
https://www.coolapk.com/feed/42497183?shareKey=YWY5ZjI5YTIzMzMxNjQwZjA3MGI~&shareUid=690846&shareFrom=com.coolapk.market_12.0.7
