### ISSUE TITLE
梦境框架已被完整安装，但未激活.

### ISSUE THREAD

**Issue by momo54181** [canyie/Dreamland#32]
设备：GIONEE GN8002S
安卓：6.0
Magisk版本：25.2官方版
Zygisk：否
Riru：已安装，载入0个模块
系统：MIUI10
SElinux：宽容模式

**Comment by shanoaice** [comment]
"Zygisk: 否"
没开 Zygisk 当然用不了，在 Magisk 设置里把 Zygisk 开启，然后重启手机
