### ISSUE TITLE
启用梦境框架模块会导致Magisk Zygisk无法正常开启

### ISSUE THREAD

**Issue by KJZH001** [canyie/Dreamland#33]
我确实不确定这个问题应该反馈到Magisk还是dreamland模块这边

不过关闭梦境框架模块后zygisk能够正常启动，所以目前我认为是梦境的问题

目前切换回到了riru模式，至少riru看起来一切工作正常

日志会在稍后贴出

**Comment by KJZH001** [comment]
---Detected Device Info---

isAB=false
isSAR=false
ramdisk=true
kernel=Linux aarch64 4.4.23+ #1 SMP PREEMPT Fri Jul 13 11:37:05 CST 2018


---System Properties---

[bastet.service.enable]: [true]
[bg_fsck.pgid]: [315]
[bt.dpbap.enable]: [1]
[bt.max.hfpclient.connections]: [2]
[build.hisi_perf_opt]: [true]
[camera.dis.flag]: [2]
[camera.drop.buffer]: [1]
[camera.ignore.chat.facebeauty]: [1]
[cdma.dormancy.mode]: [1]
[cdma.dormancy.screen]: [3]
[config.disable_consumerir]: [true]
[dalvik.vm.appimageformat]: [lz4]
[dalvik.vm.boot-dex2oat-threads]: [4]
[dalvik.vm.checkjni]: [false]
[dalvik.vm.dex2oat-Xms]: [64m]
[dalvik.vm.dex2oat-Xmx]: [512m]
[dalvik.vm.dex2oat-flags]: [--inline-max-code-units=0]
[dalvik.vm.dex2oat-threads]: [4]
[dalvik.vm.dexopt.secondary]: [true]
[dalvik.vm.heapgrowthlimit]: [384m]
[dalvik.vm.heapmaxfree]: [8m]
[dalvik.vm.heapminfree]: [4m]
[dalvik.vm.heapsize]: [512m]
[dalvik.vm.heapstartsize]: [8m]
[dalvik.vm.heaptargetutilization]: [0.75]
[dalvik.vm.image-dex2oat-Xms]: [64m]
[dalvik.vm.image-dex2oat-Xmx]: [64m]
[dalvik.vm.image-dex2oat-threads]: [4]
[dalvik.vm.isa.arm.features]: [default]
[dalvik.vm.isa.arm.variant]: [cortex-a15]
[dalvik.vm.isa.arm64.features]: [default]
[dalvik.vm.isa.arm64.variant]: [generic]
[dalvik.vm.stack-trace-file]: [/data/anr/traces.txt]
[dalvik.vm.usejit]: [true]
[dalvik.vm.usejitprofiles]: [true]
[debug.aps.current_battery]: [99]
[debug.aps.enable]: [0]
[debug.aps.lcd_fps_scence]: [60]
[debug.aps.process.name]: []
[debug.aps.scene_num]: [5]
[debug.atrace.tags.enableflags]: [0]
[debug.force_rtl]: [0]
[debug.hwui.render_dirty_regions]: [false]
[debug.sf.disable_backpressure]: [1]
[debug.sf.latch_unsignaled]: [1]
[dev.bootcomplete]: [1]
[drm.service.enabled]: [true]
[fw.max_users]: [1]
[fw.show_multiuserui]: [0]
[gsm.RBActivated0]: []
[gsm.check_is_single_pdp_sub1]: [false]
[gsm.check_is_single_pdp_sub2]: [false]
[gsm.current.phone-type]: [1,1]
[gsm.data.gsm_only_not_allow_ps]: [false]
[gsm.dualcards.switch]: [false]
[gsm.fastdormancy.mode]: [3]
[gsm.fastdormancy.screen]: [2]
[gsm.fastdormancy.time_scroff]: [4000]
[gsm.huawei.RemindDataService]: [false]
[gsm.hw.cust.ecclist0]: [000,08,118,110,119,120,122,999]
[gsm.hw.fdn.activated2]: [false]
[gsm.hw.matchnum]: [11]
[gsm.hw.matchnum.short]: [11]
[gsm.hw.matchnum.short0]: [11]
[gsm.hw.matchnum.vmn_shortcode]: [0]
[gsm.hw.matchnum0]: [11]
[gsm.hw.operator.iso-country]: [cn]
[gsm.hw.operator.isroaming]: [false]
[gsm.hw.operator.numeric]: [46001]
[gsm.hw.operator.numeric.old]: [46001]
[gsm.multipdp.plmn.matched]: [false]
[gsm.network.type]: [LTE,Unknown]
[gsm.nvcfg.resetrild]: [0]
[gsm.nvcfg.rildrestarting]: [0]
[gsm.operator.alpha]: [中国联通4G]
[gsm.operator.iso-country]: [cn]
[gsm.operator.isroaming]: [false,false]
[gsm.operator.numeric]: [46001]
[gsm.rssi.sim1]: [-108]
[gsm.sigcust.configured]: [true]
[gsm.sim.hw_atr]: [3B9F95801FC78031E073FE211B635A402783009000F9]
[gsm.sim.hw_atr1]: [null]
[gsm.sim.num.pin]: [3]
[gsm.sim.num.pin2]: [3]
[gsm.sim.num.puk]: [10]
[gsm.sim.num.puk2]: [10]
[gsm.sim.num.simlock]: [-1,-1,-1]
[gsm.sim.operator.alpha]: []
[gsm.sim.operator.iso-country]: [cn]
[gsm.sim.operator.numeric]: [46001]
[gsm.sim.preiccid_0]: [8986011]
[gsm.sim.state]: [READY,ABSENT]
[gsm.sim.updatenitz]: [-1]
[gsm.sim1.type]: [20]
[gsm.sim2.type]: [-1]
[gsm.slot1.num.pin1]: [3]
[gsm.slot1.num.pin2]: [3]
[gsm.slot1.num.puk1]: [10]
[gsm.slot1.num.puk2]: [10]
[gsm.sms.7bit.enabled]: [0]
[gsm.sms.coding.national]: [0]
[gsm.sms.max.message.size]: [0]
[gsm.sms.max.message.size0]: [0]
[gsm.sms.to.mms.textthreshold]: [0]
[gsm.sms.to.mms.textthreshold0]: [0]
[gsm.version.baseband]: [21C60B269S003C000,21C60B269S003C000]
[gsm.version.ril-impl]: [android infineon balong-ril 1.0]
[hw.browser.cfg.bookmark]: [true]
[hw.browser.cfg.downloadpath]: [true]
[hw.browser.cfg.searchengine]: [true]
[hw.browser.cfg.urllenlimit]: [2048]
[hw.lcd.density]: [480]
[hw.lcd.density.scale]: [800]
[hw.wifi.disable_auto_disc]: [true]
[hw.wifi.dns_stat]: [16,0,130,1,411]
[hw.wifipro.dns_err_count]: [22,0,0,0,0,0]
[hw.wifipro.dns_fail_count]: [21]
[hwservicemanager.ready]: [true]
[init.svc.CameraDaemon]: [running]
[init.svc.activityrecognition_1_0]: [running]
[init.svc.adbd]: [running]
[init.svc.agnsscontrol]: [running]
[init.svc.applogcat]: [stopped]
[init.svc.aptouch]: [stopped]
[init.svc.audio-ext-hal-2-0]: [running]
[init.svc.audioserver]: [running]
[init.svc.bastetd]: [running]
[init.svc.bluetooth-1-0]: [running]
[init.svc.bootanim]: [stopped]
[init.svc.cameraserver]: [running]
[init.svc.chargelogcat]: [stopped]
[init.svc.chargemonitor]: [running]
[init.svc.check_root]: [stopped]
[init.svc.configstore-hal-1-0]: [running]
[init.svc.cust_from_init]: [stopped]
[init.svc.display-hal-1-0]: [running]
[init.svc.displayeffect-1-0]: [running]
[init.svc.displayengine-hal-1-0]: [running]
[init.svc.dpeservice]: [running]
[init.svc.drm]: [running]
[init.svc.drm-hal-1-0]: [running]
[init.svc.drm-widevine-hal-1-0]: [running]
[init.svc.dubaid]: [running]
[init.svc.emc

**Comment by Howard20181** [comment]
发文件
别直接贴上来

**Comment by KJZH001** [comment]
https://pastebin.ubuntu.com/p/FZnX2gzTSm/

好了

> 发文件 别直接贴上来

我将它托管到pastebin上了

**Comment by canyie** [comment]
现在是没问题了吧
