### ISSUE TITLE
help

### ISSUE THREAD

**Issue by angousana** [canyie/Dreamland#39]
where is zygisk version of the module???

**Comment by canyie** [comment]
> Our module is all-in-one zip, if you have Zygisk enabled, it will automatically installed as Zygisk version. Since Magisk won't load Zygisk modules if Zygisk disabled, and also won't load Riru modules if Zygisk enabled, you have to re-flash the module to switch flavor.

**Comment by angousana** [comment]
![Screenshot_2024-09-03-15-30-00-129_io github huskydg magisk](https://github.com/user-attachments/assets/c6ffab3d-9821-4f30-9a3d-2365496bbcbc)
I tried disabling zygisk and using riru but it still doesn't detect riru.

**Comment by canyie** [comment]
@angousana use beta builds
