### ISSUE TITLE
Crashes on latest magisk 28001 and nougat.

### ISSUE THREAD

**Issue by Ph0rk0z** [canyie/Dreamland#41]
Attempting to install dreamland on nougat in the latest magisk causes magisk manager to close. The module is never installed.

**Comment by canyie** [comment]
This is an upstream issue. Already fixed in Magisk master branch but no releases have been published yet. See https://github.com/topjohnwu/Magisk/issues/8452 for details.

**Comment by Ph0rk0z** [comment]
Thanks, will try when they update the build. Those newer zygisk using builds keep losing root on me as well, when wifi connects or re-opening the manager. I can't create an issue until I'm running 28001+ and this is the main module I need zygisk for. Pretty much the only way to have xposed on my odex'd phone.
